function getDashboard(token){return publicCall_(function(){
  const s=session_(token),manager=isManager_(s),visitor=isVisitor_(s),sectorMap={},supervisedSectors={};
  readRows_(SHEETS.SECTORS).forEach(function(sector){sectorMap[String(sector.Id)]=sector;if(String(sector.SupervisorId)===String(s.id))supervisedSectors[String(sector.Id)]=true;});
  const docs=readRows_(SHEETS.DOCS).filter(function(d){return manager||s.sectors.indexOf('*')>=0||s.sectors.indexOf(String(d.SetorId))>=0;}),docMap={};
  docs.forEach(function(d){docMap[String(d.Id)]=d;});
  const current={};readRows_(SHEETS.EDITIONS).filter(function(e){return String(e.Status)==='Vigente';}).forEach(function(e){const key=String(e.DocumentoId),edition=String(e.Edicao),saved=current[key];if(!saved||editionNumber_(edition)>editionNumber_(saved))current[key]=edition;});
  const allTrainingMap={},trainingMap={};
  readRows_(SHEETS.TRAININGS).forEach(function(t){allTrainingMap[String(t.Id)]=t;const doc=docMap[String(t.DocumentoId)];if(doc&&String(doc.Tipo)!=='FOR'&&String(current[String(t.DocumentoId)]||'')===String(t.Edicao))trainingMap[String(t.Id)]=t;});
  const pendingParts=readRows_(SHEETS.PARTICIPANTS).filter(function(p){return String(p.Status)==='Pendente'&&trainingMap[String(p.TreinamentoId)];});
  function sectorRole(id,field){const sector=sectorMap[String(id)];return !!sector&&String(sector[field]||'')===String(s.id);}
  function canEdit(doc){return !visitor&&['Em criação','Em revisão'].indexOf(String(doc.Status))>=0&&(manager||sectorRole(doc.SetorId,'AprovadorId')||sectorRole(doc.SetorId,'SupervisorId')||(sectorRole(doc.SetorId,'ResponsavelId')&&String(doc.ResponsavelId)===String(s.id)));}
  const revision=docs.filter(function(d){return canEdit(d);}).map(function(d){const row=dashboardDocRow_(d);row.attention=sectorRole(d.SetorId,'ResponsavelId')||sectorRole(d.SetorId,'SupervisorId');return row;}).sort(function(a,b){return Number(b.attention)-Number(a.attention)||String(b.updated||'').localeCompare(String(a.updated||''));});
  const approval=docs.filter(function(d){return String(d.Status)==='Aguardando aprovação';}).map(function(d){const row=dashboardDocRow_(d),sector=sectorMap[String(d.SetorId)];row.attention=!!sector&&String(sector.AprovadorId)===String(s.id);return row;}).sort(function(a,b){return Number(b.attention)-Number(a.attention)||String(b.updated||'').localeCompare(String(a.updated||''));});
  const trainingGroups={};
  pendingParts.forEach(function(p){const t=trainingMap[String(p.TreinamentoId)],doc=docMap[String(t.DocumentoId)],sector=sectorMap[String(t.SetorId)],attention=!!sector&&(String(sector.ResponsavelId)===String(s.id)||String(sector.SupervisorId)===String(s.id));const key=String(t.DocumentoId)+'|'+String(t.Edicao)+'|'+String(t.SetorId),group=trainingGroups[key]||(trainingGroups[key]={documentId:t.DocumentoId,code:t.Codigo||doc.Codigo,title:doc.Titulo,edition:t.Edicao,sector:t.Setor||doc.Setor,pending:0,attention:attention});group.pending++;});
  const training=Object.keys(trainingGroups).map(function(key){return trainingGroups[key];}).sort(function(a,b){return Number(b.attention)-Number(a.attention)||String(a.code).localeCompare(String(b.code),'pt-BR');});
  const supervisor=s.roles.indexOf('Supervisor')>=0,audit=(manager||supervisor)?dashboardAudit_(s,docMap,allTrainingMap,supervisedSectors):[];
  return {kpis:{vigentes:docs.filter(function(d){return String(d.Status)==='Vigente';}).length,revisao:docs.filter(function(d){return ['Em criação','Em revisão'].indexOf(String(d.Status))>=0;}).length,aprovacao:docs.filter(function(d){return String(d.Status)==='Aguardando aprovação';}).length,treinamentosPendentes:pendingParts.length},pending:{revision:revision,approval:approval,training:training},audit:audit,showAudit:manager||supervisor};
});}
function dashboardDateSort_(a,b){return String(b.AtualizadoEm||'').localeCompare(String(a.AtualizadoEm||''));}
function dashboardDocRow_(doc){return {id:String(doc.Id),code:String(doc.Codigo||''),title:String(doc.Titulo||''),sector:String(doc.Setor||''),edition:String(doc.Edicao||''),responsible:String(doc.ResponsavelNome||''),updated:String(doc.AtualizadoEm||'')};}
function dashboardAudit_(s,docMap,trainingMap,supervisedSectors){
  return readTailRows_(SHEETS.AUDIT,80).reverse().map(function(a){
    let doc=null;if(String(a.Entidade)==='Documento')doc=docMap[String(a.EntidadeId)];
    else if(String(a.Entidade)==='Treinamento'){const trainingId=split_(a.EntidadeId)[0],training=trainingMap[String(trainingId)];doc=training&&docMap[String(training.DocumentoId)];}
    if(!doc||(!isManager_(s)&&!supervisedSectors[String(doc.SetorId)]))return null;
    const date=a.Data instanceof Date?a.Data.toISOString():String(a.Data||'');
    return {user:String(a.UsuarioNome||'Usuário'),action:dashboardActionLabel_(a.Acao||a['Ação']),code:String(doc.Codigo||'Documento'),date:date,documentId:String(doc.Id)};
  }).filter(Boolean).slice(0,8);
}
function dashboardActionLabel_(action){const labels={ALTEROU:'atualização',CRIOU:'criação',INICIOU_REVISAO:'início de revisão',ENVIOU_APROVACAO:'envio para aprovação',VALIDOU_FLUXO:'validação do fluxo',APROVOU:'aprovação',REJEITOU:'recusa',PUBLICOU:'publicação',SOLICITOU_OBSOLESCENCIA:'solicitação de obsolescência',APROVOU_OBSOLESCENCIA:'aprovação da obsolescência',REJEITOU_OBSOLESCENCIA:'recusa da obsolescência',TORNOU_OBSOLETO:'obsolescência',SOLICITOU_REATIVACAO:'solicitação de reativação',APROVOU_REATIVACAO:'aprovação da reativação',REJEITOU_REATIVACAO:'recusa da reativação',REATIVOU:'reativação',REGISTROU_LOTE:'registro de treinamento',AVALIOU_EFICACIA_LOTE:'avaliação de eficácia',PRORROGOU_EFICACIA:'prorrogação de eficácia'};return labels[String(action||'')]||String(action||'atualização').toLowerCase().replace(/_/g,' ');}

function listarDocumentos(token,filters){return publicCall_(function(){const s=session_(token);filters=filters||{};let rows=authorizedDocs_(s);if(filters.tipo)rows=rows.filter(function(x){return String(x.Tipo)===String(filters.tipo);});if(filters.setor)rows=rows.filter(function(x){return String(x.SetorId)===String(filters.setor);});if(filters.status==='Em criação ou revisão')rows=rows.filter(function(x){return ['Em criação','Em revisão'].indexOf(String(x.Status))>=0;});else if(filters.status)rows=rows.filter(function(x){return String(x.Status)===String(filters.status);});if(filters.q){const q=normalize_(filters.q).toLowerCase();rows=rows.filter(function(x){return [x.Codigo,x.Titulo,x.Setor,x.AutorNome].join(' ').toLowerCase().indexOf(q)>=0;});}return rows.sort(function(a,b){return String(b.AtualizadoEm).localeCompare(String(a.AtualizadoEm));}).map(cleanRow_);});}
function authorizedDocs_(s){return readRows_(SHEETS.DOCS).filter(function(d){return canSector_(s,d.SetorId);});}
function authorizedParticipants_(s){return safeRows_(SHEETS.PARTICIPANTS).filter(function(p){return canSector_(s,p.SetorId);});}

function salvarRascunho(token,payload){return publicCall_(function(){
  const s=session_(token);if(isVisitor_(s))throw new Error('Visitantes possuem acesso somente para visualização e impressão.');payload=payload||{};
  const type=normalize_(payload.tipo).toUpperCase(),title=normalize_(payload.titulo),sector=findById_(SHEETS.SECTORS,payload.setorId),doc=payload.id?findById_(SHEETS.DOCS,payload.id):null;
  if(!DOC_SECTIONS[type])throw new Error('Tipo de documento inválido.');if(!title||!sector)throw new Error('Informe título e setor.');if(!canSector_(s,sector.Id))throw new Error('Setor não autorizado.');if(doc&&!canEditDocument_(s,doc))throw new Error('Documento não pode ser editado neste estado.');
  const previous=doc?readJsonFile_(doc.FonteFileId):{},edition=doc?String(doc.Edicao):editionLabel_(1),responsibleName=doc?String(doc.ResponsavelNome||sector.ResponsavelNome||''):String(sector.ResponsavelNome||''),source={tipo:type,titulo:title,setorId:String(sector.Id),setor:String(sector.Nome),sections:normalizeSections_(type,payload.sections||[]),revisions:normalizeRevisionHistory_(type,previous.revisions,edition,payload.revisionChange,responsibleName,sector.AprovadorNome),updatedAt:now_()};
  const size=Utilities.newBlob(JSON.stringify(source)).getBytes().length;if(size>APP.MAX_SOURCE_BYTES)throw new Error('O documento excede o limite de 8 MB. Reduza o tamanho das imagens.');
  if(doc){const responsible=documentResponsibleChange_(s,doc,payload.responsavelId),file=DriveApp.getFileById(String(doc.FonteFileId));file.setContent(JSON.stringify(source));updateRow_(SHEETS.DOCS,doc._row,{Titulo:title,SetorId:sector.Id,Setor:sector.Nome,ResponsavelId:responsible.id,ResponsavelNome:responsible.name,AtualizadoEm:now_()});audit_(s,'Documento',doc.Id,'ALTEROU',{codigo:doc.Codigo,edicao:doc.Edicao});return obterDocumentoData_(s,doc.Id);}
  if(!isSectorSupervisor_(s,sector.Id))throw new Error('Somente Manager, Supervisor ou Aprovador do setor podem criar documentos.');const responsibleId=normalize_(sector.ResponsavelId);if(!responsibleId)throw new Error('O setor precisa possuir um responsável cadastrado.');const lock=LockService.getScriptLock();lock.waitLock(30000);try{const code=nextCode_(type,sector),id=uid_('doc'),folder=createDocumentFolder_(type,sector,code),file=getFolderConfig_('SOURCES').createFile(code+' - '+edition+'.json',JSON.stringify(source),MimeType.PLAIN_TEXT),newDoc={Id:id,Codigo:code,Tipo:type,Titulo:title,SetorId:sector.Id,Setor:sector.Nome,Edicao:edition,Status:'Em criação',AutorId:s.id,AutorNome:s.name,ResponsavelId:responsibleId,ResponsavelNome:normalize_(sector.ResponsavelNome)||userName_(responsibleId),FonteFileId:file.getId(),PastaId:folder.getId(),PdfFileId:'',CriadoEm:now_(),AtualizadoEm:now_(),PublicadoEm:''};appendRow_(SHEETS.DOCS,newDoc);audit_(s,'Documento',id,'CRIOU',{codigo:code,edicao:edition});return obterDocumentoData_(s,id);}finally{lock.releaseLock();}
});}

function revisionDate_(){return Utilities.formatDate(new Date(),APP.TIMEZONE,'dd/MM/yyyy');}
function normalizeRevisionHistory_(type,history,edition,change,responsible,approver){if(type==='FOR')return [];const rows=(history||[]).map(function(x){return {edicao:normalize_(x.edicao),data:normalize_(x.data),responsavel:normalize_(x.responsavel),aprovador:normalize_(x.aprovador),alteracoes:normalize_(x.alteracoes)};}).filter(function(x){return x.edicao;});let row=rows.find(function(x){return x.edicao===edition;});const first=editionNumber_(edition)===1;if(!row){row={edicao:edition,data:revisionDate_(),responsavel:normalize_(responsible),aprovador:normalize_(approver),alteracoes:first?'Criação':normalize_(change)};rows.push(row);}else{row.responsavel=normalize_(responsible)||row.responsavel;row.aprovador=normalize_(approver)||row.aprovador;if(first)row.alteracoes='Criação';else if(normalize_(change))row.alteracoes=normalize_(change);}if(!first&&!row.alteracoes)throw new Error('Informe as alterações realizadas nesta revisão.');return rows.sort(function(a,b){return editionNumber_(a.edicao)-editionNumber_(b.edicao);});}

function normalizeSections_(type,sections){const map={};(sections||[]).forEach(function(x){map[normalize_(x.title)]=sanitizeHtml_(String(x.html||''));});if(type==='POP'&&normalize_(map.Anexos)){map['Registros e evidências']=(map['Registros e evidências']||'')+'<p><strong>Anexos</strong></p>'+map.Anexos;}if(type==='IT'){if(normalize_(map['Pontos de controle']))map['Instruções passo a passo']=(map['Instruções passo a passo']||'')+'<p><strong>Pontos de controle</strong></p>'+map['Pontos de controle'];map['Registros e evidências']=(map['Registros e evidências']||'')+(map.Registros||'');if(normalize_(map.Anexos))map['Registros e evidências']+='<p><strong>Anexos</strong></p>'+map.Anexos;}return DOC_SECTIONS[type].map(function(title){return {title:title,html:map[title]||''};});}
function sanitizeHtml_(html){return String(html||'').replace(/<(script|style|iframe|object|embed)[\s\S]*?<\/\1>/gi,'').replace(/\son\w+\s*=\s*(["']).*?\1/gi,'').replace(/\s(href|src)\s*=\s*(["'])\s*javascript:[\s\S]*?\2/gi,'');}
function nextCode_(type,sector){const prefix=type+'-'+normalize_(sector.Sigla).toUpperCase()+'-';let max=0;readRows_(SHEETS.DOCS).forEach(function(d){if(String(d.Codigo).indexOf(prefix)===0)max=Math.max(max,Number(String(d.Codigo).slice(prefix.length))||0);});return prefix+String(max+1).padStart(3,'0');}
function createDocumentFolder_(type,sector,code){const typeFolder=getFolderConfig_(type),sectorFolder=getOrCreateFolder_(typeFolder,normalize_(sector.Sigla).toUpperCase());return getOrCreateFolder_(sectorFolder,code);}
function userName_(id){const u=id?findById_(SHEETS.USERS,id):null;return u?String(u.Nome):'';}
function documentResponsibleChange_(s,doc,requestedId){if(!isSectorSupervisor_(s,doc.SetorId))return {id:String(doc.ResponsavelId||''),name:String(doc.ResponsavelNome||'')};const id=normalize_(requestedId)||String(doc.ResponsavelId||'');return {id:id,name:userName_(id)||String(doc.ResponsavelNome||'')};}
function canEditDocument_(s,doc){if(isVisitor_(s)||!canSector_(s,doc.SetorId)||['Em criação','Em revisão'].indexOf(String(doc.Status))<0)return false;if(isSectorSupervisor_(s,doc.SetorId))return true;return sectorRole_(s,doc.SetorId,'ResponsavelId')&&String(doc.ResponsavelId)===s.id;}
function canManageDocumentLifecycle_(s,doc){return !isVisitor_(s)&&canSector_(s,doc.SetorId)&&(isSectorSupervisor_(s,doc.SetorId)||(sectorRole_(s,doc.SetorId,'ResponsavelId')&&String(doc.ResponsavelId)===String(s.id)));}

function obterDocumento(token,id){return publicCall_(function(){return obterDocumentoData_(session_(token),id);});}
function obterDocumentoData_(s,id){const doc=findById_(SHEETS.DOCS,id);if(!doc||!canSector_(s,doc.SetorId))throw new Error('Documento não encontrado.');const source=readJsonFile_(doc.FonteFileId),flow=readRows_(SHEETS.FLOWS).filter(function(x){return String(x.DocumentoId)===String(id)&&String(x.Edicao)===String(doc.Edicao);}).sort(function(a,b){return Number(a.Ordem)-Number(b.Ordem);}),approvals=readRows_(SHEETS.APPROVALS).filter(function(x){return String(x.DocumentoId)===String(id);}),editions=readRows_(SHEETS.EDITIONS).filter(function(x){return String(x.DocumentoId)===String(id);}),hasProposedFlow=flow.some(function(f){return String(f.Status)==='Proposto';}),sectorApprover=isSectorApprover_(s,doc.SetorId),lifecycle=canManageDocumentLifecycle_(s,doc);return {document:cleanRow_(doc),source:source,flow:flow.map(cleanRow_),approvals:approvals.map(cleanRow_),editions:editions.map(cleanRow_),trainingSummary:documentTrainingSummary_(s,doc),permissions:{edit:canEditDocument_(s,doc),submit:canEditDocument_(s,doc),validate:isManager_(s)&&String(doc.Status)==='Aguardando aprovação'&&hasProposedFlow,approve:String(doc.Status)==='Aguardando aprovação'&&sectorApprover,revise:String(doc.Status)==='Vigente'&&lifecycle,obsolete:String(doc.Status)==='Em revisão'&&lifecycle,reactivate:String(doc.Status)==='Obsoleto'&&lifecycle,manage:isManager_(s)}};}
function readJsonFile_(fileId){if(!fileId)return {};return JSON.parse(DriveApp.getFileById(String(fileId)).getBlob().getDataAsString('UTF-8'));}

function iniciarRevisao(token,docId){return publicCall_(function(){const s=session_(token),doc=findById_(SHEETS.DOCS,docId);if(!doc||String(doc.Status)!=='Vigente')throw new Error('Somente documentos vigentes podem iniciar revisão.');const allowed=!isVisitor_(s)&&(isSectorSupervisor_(s,doc.SetorId)||(sectorRole_(s,doc.SetorId,'ResponsavelId')&&String(doc.ResponsavelId)===s.id));if(!allowed)throw new Error('Sem permissão para iniciar revisão.');const next=editionLabel_(editionNumber_(doc.Edicao)+1),source=readJsonFile_(doc.FonteFileId);source.updatedAt=now_();const file=getFolderConfig_('SOURCES').createFile(doc.Codigo+' - '+next+'.json',JSON.stringify(source),MimeType.PLAIN_TEXT);updateRow_(SHEETS.DOCS,doc._row,{Edicao:next,Status:'Em revisão',FonteFileId:file.getId(),PdfFileId:'',AtualizadoEm:now_()});audit_(s,'Documento',doc.Id,'INICIOU_REVISAO',{edicao:next});return obterDocumentoData_(s,doc.Id);});}
function obsoletarDocumento(token,docId){return publicCall_(function(){const s=session_(token),doc=findById_(SHEETS.DOCS,docId);if(!doc||String(doc.Status)!=='Em revisão')throw new Error('Somente documentos em revisão podem solicitar obsolescência.');if(!canManageDocumentLifecycle_(s,doc))throw new Error('Sem permissão para solicitar a obsolescência deste documento.');const current=latestEditionByStatus_(docId,'Vigente');if(!current)throw new Error('Nenhuma edição vigente foi encontrada para retirar de circulação.');createLifecycleApproval_(doc,'Obsolescência');updateRow_(SHEETS.DOCS,doc._row,{Status:'Aguardando aprovação',AtualizadoEm:now_()});audit_(s,'Documento',doc.Id,'SOLICITOU_OBSOLESCENCIA',{edicaoVigente:current.Edicao,revisao:doc.Edicao});return obterDocumentoData_(s,doc.Id);});}
function reativarDocumento(token,docId){return publicCall_(function(){const s=session_(token),doc=findById_(SHEETS.DOCS,docId);if(!doc||String(doc.Status)!=='Obsoleto')throw new Error('Somente documentos obsoletos podem ser reativados.');if(!canManageDocumentLifecycle_(s,doc))throw new Error('Sem permissão para solicitar a reativação deste documento.');const edition=latestEditionByStatus_(docId,'Obsoleto');if(!edition)throw new Error('Nenhuma edição obsoleta foi encontrada para reativação.');createLifecycleApproval_(doc,'Reativação');updateRow_(SHEETS.DOCS,doc._row,{Status:'Aguardando aprovação',AtualizadoEm:now_()});audit_(s,'Documento',doc.Id,'SOLICITOU_REATIVACAO',{edicao:edition.Edicao});return obterDocumentoData_(s,doc.Id);});}
function latestEditionByStatus_(docId,status){return readRows_(SHEETS.EDITIONS).filter(function(e){return String(e.DocumentoId)===String(docId)&&String(e.Status)===String(status);}).sort(function(a,b){return editionNumber_(b.Edicao)-editionNumber_(a.Edicao);})[0]||null;}
function createLifecycleApproval_(doc,action){const sector=findById_(SHEETS.SECTORS,doc.SetorId),approverId=normalize_(sector&&sector.AprovadorId),approver=approverId?findById_(SHEETS.USERS,approverId):null;if(!approver||!bool_(approver.Ativo))throw new Error('O setor precisa possuir um aprovador ativo cadastrado nas Configurações.');readRows_(SHEETS.FLOWS).filter(function(f){return String(f.DocumentoId)===String(doc.Id)&&String(f.Edicao)===String(doc.Edicao);}).forEach(function(f){updateRow_(SHEETS.FLOWS,f._row,{Status:'Cancelado'});});appendRow_(SHEETS.FLOWS,{Id:uid_('flx'),DocumentoId:doc.Id,Edicao:doc.Edicao,Ordem:1,UsuarioId:approver.Id,UsuarioNome:approver.Nome||approver.Usuario,Status:'Pendente',Decisao:action,Comentario:'',Data:''});}
