function generatePdf_(doc) {
  const source=readJsonFile_(doc.FonteFileId),tempFolder=getFolderConfig_('TEMP'),document=DocumentApp.create(doc.Codigo+' - '+doc.Edicao+' - temporário'),file=DriveApp.getFileById(document.getId());
  file.moveTo(tempFolder); const body=document.getBody(); body.setMarginTop(36).setMarginBottom(36).setMarginLeft(42).setMarginRight(42);
  if(String(doc.Tipo)==='FOR')appendRepeatedForms_(body,doc,source);else{appendPdfHeader_(body,doc);body.appendParagraph('');(source.sections||[]).forEach(function(section,index){appendSectionContent_(body,(index+1)+'. '+String(section.title).toUpperCase(),String(section.html||''));});appendRevisionHistory_(body,source.revisions||[]);}
  document.saveAndClose(); Utilities.sleep(700); const pdfBlob=file.getAs(MimeType.PDF).setName(doc.Codigo+' - '+doc.Edicao+'.pdf'),pdf=DriveApp.getFolderById(String(doc.PastaId)).createFile(pdfBlob); file.setTrashed(true); return {id:pdf.getId(),name:pdf.getName()};
}
function appendPdfHeader_(container,doc){const kind={POP:'Procedimento Operacional Padrão',IT:'Instrução de Trabalho',FOR:'Formulário Controlado',POL:'Política'}[String(doc.Tipo)]||String(doc.Tipo),table=container.appendTable([['','','']]);table.setBorderWidth(1);const row=table.getRow(0),logo=row.getCell(0),center=row.getCell(1),meta=row.getCell(2);logo.setWidth(120);center.setWidth(285);meta.setWidth(145);logo.clear();const logoP=logo.appendParagraph('').setAlignment(DocumentApp.HorizontalAlignment.CENTER);try{const blob=UrlFetchApp.fetch('https://i.ibb.co/PzDD4QLk/Logo-Baldi-Vers-o-Correta-Preta.png').getBlob(),image=logoP.appendInlineImage(blob);image.setWidth(95).setHeight(55);}catch(e){logoP.appendText('Baldi').setBold(true).setFontSize(18);}center.clear();center.appendParagraph(kind).setAlignment(DocumentApp.HorizontalAlignment.CENTER).editAsText().setBold(true).setFontSize(13);center.appendParagraph('TÍTULO DO DOCUMENTO').setAlignment(DocumentApp.HorizontalAlignment.CENTER).editAsText().setFontSize(8).setForegroundColor('#666666');center.appendParagraph(String(doc.Titulo)).setAlignment(DocumentApp.HorizontalAlignment.CENTER).editAsText().setBold(true).setFontSize(14);meta.clear();[['Tipo',doc.Tipo],['Setor',doc.Setor],['Código',doc.Codigo],['Edição',doc.Edicao]].forEach(function(x){const p=meta.appendParagraph(String(x[0])+': '+String(x[1]||''));p.editAsText().setFontSize(8);p.editAsText().setBold(0,String(x[0]).length,true);});return table;}
function appendRevisionHistory_(body,rows){body.appendParagraph('REVISÕES').setHeading(DocumentApp.ParagraphHeading.HEADING2).editAsText().setBackgroundColor('#e5e7eb');const data=[['Edição','Data','Responsável','Aprovador','Alterações']].concat((rows||[]).map(function(r){return [String(r.edicao||''),String(r.data||''),String(r.responsavel||''),String(r.aprovador||''),String(r.alteracoes||'')];}));const table=body.appendTable(data);table.setBorderWidth(1);for(let c=0;c<table.getRow(0).getNumCells();c++)table.getRow(0).getCell(c).editAsText().setBold(true);}
function estimateFormCopies_(html){const source=String(html||''),plain=decodeHtml_(source.replace(/<[^>]+>/g,' ')).replace(/\s+/g,' ').trim(),lines=Math.max(1,Math.ceil(plain.length/75)),images=(source.match(/<img\b/gi)||[]).length,tables=(source.match(/<tr\b/gi)||[]).length,contentHeight=Math.max(34,lines*14+images*190+tables*24),copyHeight=104+contentHeight+14;return Math.max(1,Math.min(8,Math.floor(720/copyHeight)));}
function appendRepeatedForms_(body,doc,source){const html=String((source.sections&&source.sections[0]&&source.sections[0].html)||''),copies=estimateFormCopies_(html);for(let i=0;i<copies;i++){appendPdfHeader_(body,doc);if(normalize_(decodeHtml_(html.replace(/<[^>]+>/g,'')))||/<(img|table)\b/i.test(html))appendRichContent_(body,html);if(i<copies-1)body.appendParagraph('').setSpacingAfter(5);}}
function appendSectionContent_(body,title,html){const source=String(html||''),topicRe=/<section[^>]*class=["'][^"']*doc-topic[^"']*["'][^>]*>([\s\S]*?)<\/section>/i,match=topicRe.exec(source);if(!match){const heading=body.appendParagraph(title).setHeading(DocumentApp.ParagraphHeading.HEADING2).setForegroundColor('#111827');heading.editAsText().setBackgroundColor('#e5e7eb');appendRichContent_(body,source);return}const group=body.appendTable([['']]);group.setBorderWidth(0);const cell=group.getRow(0).getCell(0);cell.clear();const heading=cell.appendParagraph(title).setHeading(DocumentApp.ParagraphHeading.HEADING2).setForegroundColor('#111827');heading.editAsText().setBackgroundColor('#e5e7eb');appendTopicContent_(cell,match[1]);const remaining=source.slice(0,match.index)+source.slice(match.index+match[0].length);appendRichContent_(body,remaining);}
function appendTopicContent_(container,inner){const numberMatch=/<strong[^>]*class=["'][^"']*doc-topic-number[^"']*["'][^>]*>([\s\S]*?)<\/strong>/i.exec(inner),contentMatch=/<div[^>]*class=["'][^"']*topic-content[^"']*["'][^>]*>([\s\S]*)<\/div>/i.exec(inner);if(numberMatch)container.appendParagraph(decodeHtml_(numberMatch[1].replace(/<[^>]+>/g,'')).trim()).editAsText().setBold(true);appendRichBlocks_(container,contentMatch?contentMatch[1]:inner);}
function appendRichContent_(body,html){const source=String(html||''),topicRe=/<section[^>]*class=["'][^"']*doc-topic[^"']*["'][^>]*>([\s\S]*?)<\/section>/gi;let match,found=false;while((match=topicRe.exec(source))){found=true;const numberMatch=/<strong[^>]*class=["'][^"']*doc-topic-number[^"']*["'][^>]*>([\s\S]*?)<\/strong>/i.exec(match[1]),contentMatch=/<div[^>]*class=["'][^"']*topic-content[^"']*["'][^>]*>([\s\S]*)<\/div>/i.exec(match[1]),topicTable=body.appendTable([['']]);topicTable.setBorderWidth(0);const cell=topicTable.getRow(0).getCell(0);cell.clear();if(numberMatch)cell.appendParagraph(decodeHtml_(numberMatch[1].replace(/<[^>]+>/g,'')).trim()).editAsText().setBold(true);appendRichBlocks_(cell,contentMatch?contentMatch[1]:match[1]);}if(!found)appendRichBlocks_(body,source);}
function appendRichBlocks_(body,html){let rest=String(html||''),regex=/(<table[\s\S]*?<\/table>|<img[^>]+>)/i,match;while((match=regex.exec(rest))){appendTextHtml_(body,rest.slice(0,match.index));const block=match[0];if(/^<table/i.test(block))appendHtmlTable_(body,block);else appendHtmlImage_(body,block);rest=rest.slice(match.index+block.length);}appendTextHtml_(body,rest);}
function appendTextHtml_(body,html){const text=decodeHtml_(String(html||'').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<\/(p|div|h[1-6]|li)>/gi,'\n').replace(/<li[^>]*>/gi,'• ').replace(/<[^>]+>/g,''));text.split(/\n+/).map(function(x){return x.trim();}).filter(Boolean).forEach(function(line){body.appendParagraph(line);});}
function appendHtmlTable_(body,html){const rows=[],rowRe=/<tr[^>]*>([\s\S]*?)<\/tr>/gi;let rm;while((rm=rowRe.exec(html))){const cells=[],cellRe=/<t[dh][^>]*>([\s\S]*?)<\/t[dh]>/gi;let cm;while((cm=cellRe.exec(rm[1])))cells.push(decodeHtml_(cm[1].replace(/<[^>]+>/g,'')).trim());if(cells.length)rows.push(cells);}if(rows.length)body.appendTable(rows);}
function appendHtmlImage_(body,tag){const m=/src=["']data:([^;]+);base64,([^"']+)["']/i.exec(tag);if(!m)return;try{const image=body.appendImage(Utilities.newBlob(Utilities.base64Decode(m[2]),m[1],'imagem'));if(image.getWidth()>500){const ratio=500/image.getWidth();image.setWidth(500).setHeight(Math.round(image.getHeight()*ratio));}}catch(e){body.appendParagraph('[Imagem não pôde ser processada]');}}
function decodeHtml_(s){return String(s||'').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'");}
function obterPdf(token,docId,edition){return publicCall_(function(){const s=session_(token),doc=findById_(SHEETS.DOCS,docId);if(!doc||!canSector_(s,doc.SetorId))throw new Error('Documento não encontrado.');let fileId=doc.PdfFileId;if(edition){const e=readRows_(SHEETS.EDITIONS).find(function(x){return String(x.DocumentoId)===String(docId)&&String(x.Edicao)===String(edition);});if(e)fileId=e.PdfFileId;}if(!fileId)throw new Error('PDF ainda não disponível.');return {id:String(fileId),downloadUrl:'https://drive.google.com/uc?export=download&id='+fileId,previewUrl:'https://drive.google.com/file/d/'+fileId+'/preview'};});}
function imprimirDocumento(token,docId,edition){return obterPdf(token,docId,edition);}

function doGet(e){const props=PropertiesService.getScriptProperties();if(props.getProperty('CONFIGURED_VERSION')!==APP.VERSION){const setup=configurarPlataforma();if(!setup.ok)throw new Error(setup.error&&setup.error.message?setup.error.message:'Falha na configuração inicial.');props.setProperty('CONFIGURED_VERSION',APP.VERSION);}if(e&&e.parameter&&e.parameter.health==='1')return ContentService.createTextOutput(JSON.stringify(healthCheck_())).setMimeType(ContentService.MimeType.JSON);const tpl=HtmlService.createTemplateFromFile('Index');tpl.appName=APP.NAME;tpl.version=APP.VERSION;return tpl.evaluate().setTitle(APP.NAME).setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL).addMetaTag('viewport','width=device-width, initial-scale=1');}
function healthCheck_(){const expected=Object.keys(HEADERS),existing=expected.filter(function(name){return !!ss_().getSheetByName(name);}),folderKeys=['DOCS','POP','IT','FOR','POL','SOURCES','IMAGES','TEMP'],folders=folderKeys.filter(function(key){try{return !!getFolderConfig_(key);}catch(e){return false;}}),authReady=readRows_(SHEETS.USERS).some(function(u){return bool_(u.Ativo)&&normalize_(u.Usuario)&&normalize_(u.Senha);});return {ok:existing.length===expected.length&&folders.length===folderKeys.length&&authReady,version:APP.VERSION,sheets:{expected:expected.length,ready:existing.length},folders:{expected:folderKeys.length,ready:folders.length},authentication:authReady?'ready':'error',timestamp:now_()};}
function include(filename){return HtmlService.createHtmlOutputFromFile(filename).getContent();}
